# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=200)),
                ('text', models.TextField(max_length=1024)),
            ],
        ),
    ]
