# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='description',
        ),
    ]
